# Generated by Django 6.0.2 on 2026-03-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sold_in_pairs',
            field=models.BooleanField(default=False, help_text='Check this if the item is imported as a pair (like Headlights or Shocks).'),
        ),
        migrations.AddField(
            model_name='product',
            name='single_piece_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Premium price if a customer breaks the pair and buys only one side.', max_digits=10, null=True),
        ),
    ]
