# Generated by Django 6.0.2 on 2026-08-17 13:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_sold_in_pairs_product_single_piece_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_margin_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Overrides the shop's minimum margin for this part only. Blank = use the shop setting.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('500.00'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='price_is_manual',
            field=models.BooleanField(default=False, help_text='Set automatically when a human edits the price. Once true, receiving a shipment will not silently overwrite the price -- it is offered as a suggestion.'),
        ),
        migrations.AddField(
            model_name='product',
            name='split_price_mode',
            field=models.CharField(choices=[('PERCENT', 'Percentage of pair price'), ('FIXED', 'Fixed amount')], default='PERCENT', help_text='PERCENT keeps the single-piece price locked to the pair price forever. FIXED pins an exact cedi amount that never moves.', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='split_price_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), help_text='What one side costs when the pair is broken, as a % of the pair price. 60 means one headlight sells for 60% of the pair price.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='suggested_price_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='suggested_price_source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='suggested_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='A price a shipment wanted to apply but could not, because the price is manual.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='single_piece_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='FIXED mode only: the exact price for one side of a broken pair. Ignored while the split rule is set to PERCENT.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PriceChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(default='selling_price', max_length=40)),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('MANUAL', 'Edited by hand'), ('SHIPMENT', 'Shipment received'), ('IMPORT', 'Excel import'), ('COST_SYNC', 'Cost re-synced from batches'), ('SUGGESTION', 'Suggested price accepted')], max_length=20)),
                ('was_applied', models.BooleanField(default=True, help_text='False = held back as a suggestion only')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='products_pr_product_7ea013_idx')],
            },
        ),
    ]
