# Generated by Django 6.0.2 on 2026-08-17 16:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_location_min_margin_percentage'),
        ('products', '0003_product_min_margin_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text="e.g. 'Easter Clearance' or 'Old Corolla stock'", max_length=150)),
                ('description', models.TextField(blank=True, help_text='Why this promotion exists. Shown to managers.')),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentage off the normal price'), ('AMOUNT', 'Fixed amount off (GHS)'), ('FIXED', 'Sell at this exact price (GHS)')], default='PERCENT', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percent for PERCENT (e.g. 15 = 15% off), cedis for AMOUNT/FIXED.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('applies_to_all', models.BooleanField(default=False, help_text='Apply to the entire catalogue. Use with care.')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, help_text='Leave blank to run until switched off.', null=True)),
                ('allow_below_cost', models.BooleanField(default=False, help_text='Tick ONLY for a deliberate loss-leader. Without this, the promotion suspends itself on any part it would sell below landed cost.')),
                ('categories', models.ManyToManyField(blank=True, help_text='Includes every sub-category underneath.', related_name='promotions', to='products.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotions', to=settings.AUTH_USER_MODEL)),
                ('locations', models.ManyToManyField(blank=True, help_text='Leave empty to run in every shop.', related_name='promotions', to='location.location')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='products.product')),
            ],
            options={
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='products_pr_is_acti_3066af_idx')],
            },
        ),
    ]
