# Generated by Django 6.0.2 on 2026-02-08 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('YANGO', 'Yango'), ('UBER', 'Uber'), ('BOLT', 'Bolt'), ('IN_HOUSE', 'In-House Rider'), ('DHL', 'DHL / FedEx'), ('OTHER', 'Other')], default='IN_HOUSE', max_length=20)),
                ('rider_name', models.CharField(blank=True, help_text='Name of the rider picking up', max_length=255)),
                ('rider_phone', models.CharField(blank=True, help_text='Phone number for the rider', max_length=20)),
                ('vehicle_details', models.CharField(blank=True, help_text='License Plate / Bike Model / Color', max_length=255)),
                ('tracking_reference', models.CharField(blank=True, help_text='Yango Link, Tracking ID, or Ride Ref', max_length=255)),
                ('destination_address', models.TextField(help_text='Full delivery address provided by customer')),
                ('google_maps_link', models.URLField(blank=True, help_text='Pinned location link')),
                ('delivery_fee_charged', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount charged to customer on receipt', max_digits=10)),
                ('cost_to_business', models.DecimalField(decimal_places=2, default=0.0, help_text='Actual cost paid to Yango/Rider', max_digits=10)),
                ('proof_of_pickup', models.ImageField(blank=True, help_text='Photo of rider with items or app screenshot', null=True, upload_to='deliveries/pickup/')),
                ('proof_of_delivery', models.ImageField(blank=True, help_text='Photo of item at destination', null=True, upload_to='deliveries/dropoff/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Pickup'), ('DISPATCHED', 'Dispatched / In Transit'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed / Returned')], default='PENDING', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Driver instructions or issues')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invoice_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of items before tax', max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Final Bill Amount', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of all SalePayments', max_digits=12)),
                ('change_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment / Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Fully Refunded'), ('PARTIAL', 'Partially Refunded'), ('HOLD', 'On Hold / Parked')], default='PENDING', max_length=20)),
                ('order_type', models.CharField(choices=[('WALK_IN', 'Walk-In'), ('DELIVERY', 'Delivery'), ('PICKUP', 'Store Pickup'), ('ONLINE', 'Online Order')], default='WALK_IN', max_length=20)),
                ('fulfillment_status', models.CharField(choices=[('FULFILLED', 'Items Handed Over'), ('UNFULFILLED', 'Pending Delivery/Pickup'), ('PARTIAL', 'Partially Fulfilled')], default='FULFILLED', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_refunded', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MOMO', 'Mobile Money'), ('CARD', 'Card'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CREDIT', 'Store Credit / On Account')], max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='Transaction ID, Cheque Number, or Receipt Ref', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=100)),
                ('tax_rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, help_text='Cash amount in drawer at start', max_digits=12)),
                ('closing_balance_expected', models.DecimalField(decimal_places=2, default=0.0, help_text='System calculated expected cash', max_digits=12)),
                ('closing_balance_actual', models.DecimalField(blank=True, decimal_places=2, help_text='Actual cash counted by cashier', max_digits=12, null=True)),
                ('total_cash_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_momo_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_card_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('DISCREPANCY', 'Closed with Discrepancy')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Explanation for discrepancies')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_sessions', to='location.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
