# Generated by Django 6.0.2 on 2026-08-17 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_credit_limit_customer_customer_type_and_more'),
        ('inventory', '0006_alter_stockbatch_options_shipment_notes_and_more'),
        ('location', '0003_location_min_margin_percentage'),
        ('products', '0003_product_min_margin_percentage_and_more'),
        ('sales', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItemBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per piece from this batch', max_digits=12)),
                ('pieces_restocked', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='registersession',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='salepayment',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='registersession',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registersession',
            name='total_bank_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='registersession',
            name='total_cash_refunds',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cash paid back out of the drawer', max_digits=12),
        ),
        migrations.AddField(
            model_name='registersession',
            name='total_cheque_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='registersession',
            name='total_credit_extended',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Value handed over unpaid during this shift', max_digits=12),
        ),
        migrations.AddField(
            model_name='registersession',
            name='total_till_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cash taken out of the drawer for expenses', max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='has_price_override',
            field=models.BooleanField(default=False, help_text='A line on this sale was authorised below the margin floor'),
        ),
        migrations.AddField(
            model_name='sale',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Value of goods refunded off this invoice', max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='COGS snapshot: exact cost of the batches this sale consumed', max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='below_floor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='System price before haggling', max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='override_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='pieces_per_unit',
            field=models.PositiveSmallIntegerField(default=1, help_text='2 for a pair, otherwise 1'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='quantity_refunded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sell_mode',
            field=models.CharField(choices=[('PIECE', 'Piece'), ('PAIR', 'Pair'), ('SINGLE', 'Single (broken pair)')], default='PIECE', max_length=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Exact cost of the batches consumed -- this is COGS', max_digits=12),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='entry_type',
            field=models.CharField(choices=[('SALE', 'Payment at point of sale'), ('DEBT', 'Debt settlement'), ('CHANGE', 'Change given back'), ('REFUND', 'Refund paid out')], default='SALE', max_length=10),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='register_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.registersession'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='is_refunded',
            field=models.BooleanField(default=False, help_text='True once every unit on this line is refunded'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Billed units (pairs, singles or pieces)'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, help_text='Landed cost per unit (average)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price actually charged per unit', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Positive = money in. Negative = change or refund out.', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='registersession',
            index=models.Index(fields=['location', 'status'], name='sales_regis_locatio_fe4503_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['location', '-created_at'], name='sales_sale_locatio_919f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', '-created_at'], name='sales_sale_status_c95ece_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale'], name='sales_salei_sale_id_413ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['product'], name='sales_salei_product_f87493_idx'),
        ),
        migrations.AddIndex(
            model_name='salepayment',
            index=models.Index(fields=['register_session', 'payment_method'], name='sales_salep_registe_f275ec_idx'),
        ),
        migrations.AddIndex(
            model_name='salepayment',
            index=models.Index(fields=['sale'], name='sales_salep_sale_id_d49c20_idx'),
        ),
        migrations.AddField(
            model_name='saleitembatch',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_allocations', to='inventory.stockbatch'),
        ),
        migrations.AddField(
            model_name='saleitembatch',
            name='sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_lines', to='sales.saleitem'),
        ),
        migrations.AddIndex(
            model_name='saleitembatch',
            index=models.Index(fields=['batch'], name='sales_salei_batch_i_22f133_idx'),
        ),
    ]
