# Generated by Django 6.0.2 on 2026-08-17 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_promotion'),
        ('sales', '0004_backfill_money_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='promotion',
            field=models.ForeignKey(blank=True, help_text='The promotion that authorised this price', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='products.promotion'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='below_floor',
            field=models.BooleanField(default=False, help_text="Sold under cost + the shop's minimum margin"),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='override_by',
            field=models.ForeignKey(blank=True, help_text='Legacy: manager who authorised a till-level override', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_overrides', to=settings.AUTH_USER_MODEL),
        ),
    ]
