# Generated by Django 6.0.2 on 2026-03-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum amount this person is allowed to owe. 0 means no credit allowed.', max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('WALK_IN', 'Regular Walk-in'), ('MECHANIC', 'Mechanic / Fitter'), ('RETAILER', 'Retail Shop / Reseller')], default='WALK_IN', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='workshop_name',
            field=models.CharField(blank=True, help_text='e.g. Master Kojo Motors', max_length=255, null=True),
        ),
    ]
