# Generated by Django 6.0.2 on 2026-08-17 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='register_session',
            field=models.ForeignKey(blank=True, help_text='The open drawer this cash came out of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='sales.registersession'),
        ),
    ]
