# Generated by Django 6.0.2 on 2026-02-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requires_password_change',
            field=models.BooleanField(default=False, help_text='If True, user must change password on next login.'),
        ),
    ]
