# Generated by Django 6.0.2 on 2026-02-08 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.location'),
        ),
    ]
