# Generated by Django 6.0.2 on 2026-03-25 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(help_text='e.g., LSA20251018', max_length=100, unique=True)),
                ('supplier_name', models.CharField(max_length=255)),
                ('date_shipped', models.DateField(blank=True, null=True)),
                ('exchange_rate', models.DecimalField(decimal_places=4, help_text='Current exchange rate: 1 USD = X GHS', max_digits=10)),
                ('total_freight_usd', models.DecimalField(decimal_places=2, help_text='Total cost of shipping & clearing in USD', max_digits=12)),
                ('total_cbm', models.DecimalField(decimal_places=4, help_text='Total volume of the container in CBM', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending (In Transit / Clearing)'), ('RECEIVED', 'Received into Stock')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Number of pairs/pieces')),
                ('unit_cost_usd', models.DecimalField(decimal_places=2, help_text='Supplier price per piece in USD', max_digits=10)),
                ('total_line_cbm', models.DecimalField(decimal_places=4, help_text='Total CBM for this line item', max_digits=10)),
                ('outside_sale_price_ghs', models.DecimalField(decimal_places=2, help_text='Your manual selling price in GHS', max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.shipment')),
            ],
        ),
    ]
