# Generated by Django 6.0.2 on 2026-03-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_shipment_shipmentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='outside_sale_price_ghs',
            field=models.DecimalField(decimal_places=2, help_text='Your selling price (Per PAIR if applicable, else Piece)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='quantity',
            field=models.IntegerField(help_text='Number of PIECES (e.g. 10)'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='unit_cost_usd',
            field=models.DecimalField(decimal_places=2, help_text='Supplier price per PIECE in USD', max_digits=10),
        ),
    ]
