# Generated by Django 6.0.2 on 2026-08-17 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_shipmentitem_outside_sale_price_ghs_and_more'),
        ('location', '0003_location_min_margin_percentage'),
        ('products', '0003_product_min_margin_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockbatch',
            options={'ordering': [models.OrderBy(models.F('expiry_date'), nulls_last=True), 'received_date', 'id']},
        ),
        migrations.AddField(
            model_name='shipment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='received_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_shipments', to='location.location'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='update_selling_price',
            field=models.BooleanField(default=True, help_text='Untick to receive this line as stock only, leaving the shop price untouched.'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='initial_quantity',
            field=models.IntegerField(default=0, help_text='Pieces this batch arrived with (never changes)'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(choices=[('DAMAGE', 'Damaged'), ('THEFT', 'Theft'), ('EXPIRED', 'Expired'), ('CORRECTION', 'Inventory Count Correction'), ('RETURN', 'Customer Return (Restock)'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='batch_number',
            field=models.CharField(blank=True, db_index=True, help_text='Container / lot reference, e.g. LSA20251018', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, help_text='Cost per piece for this specific batch', max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Pieces still on the shelf from this batch'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['location', 'quantity'], name='inventory_s_locatio_33baa7_idx'),
        ),
    ]
