# Generated by Django 6.0.2 on 2026-08-17 13:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='min_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Minimum gross margin over landed cost, in %. 10 means nothing may be sold below cost + 10% unless a manager authorises it.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('500.00'))]),
        ),
    ]
