# Generated by Django 6.0.2 on 2026-02-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyShopSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0.0, help_text='Gross Profit (Sales - Cost of Goods)', max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of approved expenses for the day', max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Profit - Total Expenses', max_digits=15)),
                ('total_tax_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_discount_given', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('target_for_the_day', models.DecimalField(decimal_places=2, default=0.0, help_text='What was the target set for this specific date?', max_digits=15)),
                ('target_achievement_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('items_sold_count', models.PositiveIntegerField(default=0)),
                ('average_basket_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cash_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('momo_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('card_payments', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            options={
                'verbose_name_plural': 'Daily Shop Summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SlowMovingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sold_date', models.DateField()),
                ('days_since_last_sale', models.PositiveIntegerField()),
                ('current_stock_quantity', models.IntegerField()),
                ('estimated_tied_capital', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
